# Generated by Django 2.2.5 on 2019-09-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number1', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number2', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rescued', models.BooleanField(blank=True, null=True)),
                ('died', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('person_pic1', models.ImageField(default='collection/None/no-img.jpg', upload_to='collection/')),
                ('person_pic2', models.ImageField(default='collection/None/no-img.jpg', upload_to='collection/')),
                ('person_pic3', models.ImageField(default='collection/None/no-img.jpg', upload_to='collection/')),
            ],
        ),
    ]
